services:
  web:
    image: odoo:18
    ports:
      - "${HTTP_PORT}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=${DB_HOST}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped
    command: ["odoo", "-c", "/etc/odoo/odoo.conf", "-i", "base,sale,purchase,stock,account,hr,point_of_sale", "-d", "odoo_db"]
    # command: ["odoo", "-c", "/etc/odoo/odoo.conf"]


  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: odoo18-db

volumes:
  db_data: